# Generated by Django 3.1.4 on 2020-12-30 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="homework",
            name="deadline",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="homeworkresult",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
